name: restaurant_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.3
  provider: ^6.0.0
  dotted_border: ^2.0.0+1
  flutter_staggered_animations: ^1.0.0
  cool_alert: ^1.1.0
  shimmer: ^2.0.0
  lottie: ^1.2.1
  sqflite: ^2.0.0+4
  introduction_screen: ^2.1.0
  iconsax: ^0.0.8
  flashy_tab_bar2: ^0.0.3
  pull_to_refresh: ^2.0.0
  android_alarm_manager_plus: ^2.0.2
  flutter_local_notifications: ^9.0.0
  intl: ^0.17.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  sliding_up_panel: ^2.0.0+1
  loading_indicator: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  mockito: ^5.0.16
  build_runner: ^2.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#000000"
  image_dark: assets/images/splash_logo_dark.png
  android: true
  ios: true
  web: false


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/
